### ISSUE TITLE
dynamic_vino_sample use case

### ISSUE THREAD

**Issue by portgasray** [intel/ros2_openvino_toolkit#164]
with `ros2 launch dynamic_vino_sample pipeline_segmentation.launch.py `
* the error information:
```
[ ERROR ] Error loading xmlfile: /opt/openvino_toolkit/models/segmentation/output/FP16/frozen_inference_graph.xml, File was not found at line: 1 pos: 0
```
![dynamic_vino_sample_error](https://user-images.githubusercontent.com/17681580/69693476-63d0d200-1110-11ea-997f-d6bf0b4ca677.png)

the config file `ros2_openvino_toolkit/sample/param/pipeline_segmentation.yaml`

```
Pipelines:
- name: segmentation
  inputs: [RealSenseCameraTopic]
  infers:
    - name: ObjectSegmentation
      model: /opt/openvino_toolkit/models/segmentation/output/FP16/frozen_inference_graph.xml
      engine: "HETERO:CPU,GPU,MYRIAD"
      label: to/be/set/xxx.labels
      batch: 1
      confidence_threshold: 0.5
  outputs: [ImageWindow, RosTopic, RViz]
  connects:
    - left: RealSenseCameraTopic
      right: [ObjectSegmentation]
    - left: ObjectSegmentation
      right: [ImageWindow]
    - left: ObjectSegmentation
      right: [RosTopic]
    - left: ObjectSegmentation
      right: [RViz]

OpenvinoCommon:
```
