### ISSUE TITLE
Resolution 848x480 FPS 60 with realsense D455, No data received in CameraTopic instance

### ISSUE THREAD

**Issue by chenjunnn** [intel/ros2_openvino_toolkit#216]
ROS version : Galactic

When I first tried ros2_openvino_toolkit using 640x360 fps 90 with D455, it works well. As I tried the 848x480 60fps settings, the ros2_openvino_toolkit keeps showing debug info of `No data received in CameraTopic instance` and there is no output.

This is my `pipeline_object_topic.yaml`
```
Pipelines:
- name: object
  inputs: [RealSenseCameraTopic]
  infers:
    - name: ObjectDetection
      model: /home/pioneer/Documents/ros2_ws/models/frozen_inference_graph.xml
      engine: CPU
      label: /home/pioneer/Documents/coco_labels.labels
      batch: 1
      confidence_threshold: 0.2
      enable_roi_constraint: false # set enable_roi_constraint to false if you don't want to make the inferred ROI (region of interest) constrained into the camera frame
  outputs: [RosTopic, RViz]
  connects:
    - left: RealSenseCameraTopic
      right: [ObjectDetection]
    - left: ObjectDetection
      right: [RosTopic]
    - left: ObjectDetection
      right: [RViz]

OpenvinoCommon:
```

And some info of the `realsense2_camera_node` 
```
[realsense2_camera_node-1] [INFO] [1634048165.799294774] [RealSenseCameraNode]: Done Setting Dynamic reconfig parameters.
[realsense2_camera_node-1] [INFO] [1634048165.800335933] [RealSenseCameraNode]: depth stream is enabled - width: 848, height: 480, fps: 90, Format: Z16
[realsense2_camera_node-1] [INFO] [1634048165.800931335] [RealSenseCameraNode]: color stream is enabled - width: 640, height: 360, fps: 90, Format: RGB8
[realsense2_camera_node-1] [INFO] [1634048165.802457161] [RealSenseCameraNode]: gyro stream is enabled - fps: 400
[realsense2_camera_node-1] [INFO] [1634048165.802503305] [RealSenseCameraNode]: accel stream is enabled - fps: 200
[realsense2_camera_node-1] [INFO] [1634048165.802513081] [RealSenseCameraNode]: setupPublishers...
[realsense2_camera_node-1] [INFO] [1634048165.806129207] [RealSenseCameraNode]: Start publisher IMU
[realsense2_camera_node-1] [INFO] [1634048165.807159882] [RealSenseCameraNode]: setupStreams...
[realsense2_camera_node-1] [INFO] [1634048165.838376522] [RealSenseCameraNode]: SELECTED BASE:Depth, 0
[realsense2_camera_node-1] [WARN] [1634048165.839381267] [RealSenseCameraNode]: Could not set param: rgb_camera.auto_exposure_roi.bottom with 359Range: [0, 359]: parameter 'rgb_camera.auto_exposure_roi.bottom' could not be set: Parameter {} doesn't comply with integer range.
[realsense2_camera_node-1] [INFO] [1634048165.840813639] [RealSenseCameraNode]: RealSense Node Is Up!
```
rqt_graph:
![image](https://user-images.githubusercontent.com/57067221/136981422-2d31aba9-0481-4db5-98ff-1d49fa6b77b8.png)
